exec(open(__file__.replace('inspect_forms.py','moodle_read.py'),encoding='utf8').read().split('with sync_playwright() as p:')[0])
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    context=browser.new_context(ignore_https_errors=True)
    page=context.new_page()
    page.goto(credentials['url'])
    page.locator('#username').fill(credentials['username']);page.locator('#password').fill(credentials['password']);page.locator('#loginbtn').click()
    page.wait_for_load_state('domcontentloaded')
    for mid in [2907,2908,2909]:
        page.goto(f'https://cursos3.e-itesca.edu.mx/mod/assign/view.php?id={mid}')
        page.get_by_role('button',name='Agregar entrega',exact=True).click()
        page.locator('.filemanager').wait_for()
        page.locator('input[name=submitbutton]').wait_for(state='visible')
        text=page.locator('body').inner_text()
        (OUT/f'{mid}-form.txt').write_text(text,encoding='utf8')
        print('FORM',mid,text[text.find('Archivos enviados'):text.find('Actividad previa')],flush=True)
        print('FILE INPUTS',page.locator('input[type=file]').count(),flush=True)
        print('BUTTONS',page.locator('button,input[type=submit],a[role=button]').evaluate_all('(els)=>els.map(e=>({text:e.innerText,value:e.value,cls:e.className,title:e.title}))'),flush=True)
    browser.close()
