exec(open(__file__.replace('inspect_picker.py','moodle_read.py'),encoding='utf8').read().split('with sync_playwright() as p:')[0])
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    context=browser.new_context(ignore_https_errors=True)
    page=context.new_page()
    page.goto(credentials['url'])
    page.locator('#username').fill(credentials['username']);page.locator('#password').fill(credentials['password']);page.locator('#loginbtn').click()
    page.wait_for_load_state('domcontentloaded')
    page.goto('https://cursos3.e-itesca.edu.mx/mod/assign/view.php?id=2908')
    page.get_by_role('button',name='Agregar entrega',exact=True).click()
    page.get_by_title('Agregar...',exact=True).click()
    page.get_by_text('Subir un archivo',exact=True).click()
    page.locator('input[type=file]').wait_for(state='attached')
    dialog=page.locator('.moodle-dialogue-focused')
    print(dialog.inner_text(),flush=True)
    print(page.locator('input[type=file]').evaluate_all('(els)=>els.map(e=>({name:e.name,id:e.id}))'),flush=True)
    print(dialog.locator('input:not([type=hidden]),button').evaluate_all('(els)=>els.map(e=>({tag:e.tagName,type:e.type,name:e.name,txt:e.innerText}))'),flush=True)
    browser.close()
